/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedTestImport } from './routes/_authed/test'
import { Route as AuthedMusicRoomGuildImport } from './routes/_authed/music-room.$guild'

// Create/Update Routes

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedTestRoute = AuthedTestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedMusicRoomGuildRoute = AuthedMusicRoomGuildImport.update({
  id: '/music-room/$guild',
  path: '/music-room/$guild',
  getParentRoute: () => AuthedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_authed/test': {
      id: '/_authed/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthedTestImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/music-room/$guild': {
      id: '/_authed/music-room/$guild'
      path: '/music-room/$guild'
      fullPath: '/music-room/$guild'
      preLoaderRoute: typeof AuthedMusicRoomGuildImport
      parentRoute: typeof AuthedImport
    }
  }
}

// Create and export the route tree

interface AuthedRouteChildren {
  AuthedTestRoute: typeof AuthedTestRoute
  AuthedMusicRoomGuildRoute: typeof AuthedMusicRoomGuildRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedTestRoute: AuthedTestRoute,
  AuthedMusicRoomGuildRoute: AuthedMusicRoomGuildRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/test': typeof AuthedTestRoute
  '/music-room/$guild': typeof AuthedMusicRoomGuildRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/test': typeof AuthedTestRoute
  '/music-room/$guild': typeof AuthedMusicRoomGuildRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/test': typeof AuthedTestRoute
  '/_authed/music-room/$guild': typeof AuthedMusicRoomGuildRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/test' | '/music-room/$guild'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/test' | '/music-room/$guild'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/test'
    | '/_authed/music-room/$guild'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/test",
        "/_authed/music-room/$guild"
      ]
    },
    "/_authed/test": {
      "filePath": "_authed/test.tsx",
      "parent": "/_authed"
    },
    "/_authed/music-room/$guild": {
      "filePath": "_authed/music-room.$guild.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */
