[[roles]]
name = "echidna"
# Define a list of routes with the syntax "Http-Method /path"
routes = ["GET /v1/openvpn/status", "PUT /v1/openvpn/status"]
# Define an authentication method with its parameters
auth = "none"