services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - SERVER_COUNTRIES=United States
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://google.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  echidna:
    build: .
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun
    environment:
      - DISCORD_AUTH_CLIENT_SECRET=${DISCORD_AUTH_CLIENT_SECRET}
      - DISCORD_BOT_CLIENT_ID=${DISCORD_BOT_CLIENT_ID}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - DISCORD_DB_PROFILE=${DISCORD_DB_PROFILE}
      - DISCORD_OWNER_ID=${DISCORD_OWNER_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RUNPOD_TOKEN=${RUNPOD_TOKEN}
      - WAIFU_GENERATOR_ENDPOINT=${WAIFU_GENERATOR_ENDPOINT}
      - DANBOORU_ENDPOINT=${DANBOORU_ENDPOINT}
      - API_URL=${API_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - NODE_ENV=${NODE_ENV}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_URL=${OPENROUTER_URL}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_USER=${OPENVPN_USER}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - CIVITAI_API_KEY=${CIVITAI_API_KEY}
